# Generated by Django 4.2 on 2023-05-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CfgOptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_acc_name', models.CharField(max_length=128, verbose_name='操作账号名')),
                ('opt_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('opt_name', models.CharField(max_length=128, verbose_name='操作配置名')),
                ('opt_type', models.CharField(max_length=128, verbose_name='操作类型')),
            ],
        ),
        migrations.DeleteModel(
            name='Xmlcfg',
        ),
    ]
