# Generated by Django 4.2.2 on 2023-07-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mailUniqueId',
            fields=[
                ('mail_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='邮件唯一id')),
            ],
        ),
    ]
