"""
Django settings for GameAdmin project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

#https://www.devart.com/dbforge/mysql/how-to-install-mysql-on-ubuntu/ 安装mysql5.7
#wget https://dev.mysql.com/get/mysql-apt-config_0.8.12-1_all.deb
#apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 467B942D3A79BD29
#dpkg -i mysql-apt-config_0.8.12-1_all.deb
#apt update
#apt install -f mysql-client=5.7* mysql-community-server=5.7* mysql-server=5.7*

from pathlib import Path
import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-71-&ks_fv6e303i025x05_5^yo-hhi*!u)kbj8bio!x2bq566k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'account.apps.AccountConfig',
    'server.apps.ServerConfig',
    'mail.apps.MailConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GameAdmin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
         'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GameAdmin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'admin',
        'USER': 'root',
        'PASSWORD': 'Ws123456',
        'HOST': "localhost",
        'PORT': 3306,
        'CHARSET': 'utf8'
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media').replace('\\', '/') 
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
AUTH_USER_MODEL = 'account.Account'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#页面左边列表
ACC_SELECT_LIST = [
    [
        {
            'name': '账号操作管理',
            'key' : 'title',
            'path' : 'accoptid'
        },
        {
            'name' : '账号展示',
            'key' : 'accShowSelect',
            'path' : '/account_show/'
        },
        {
            'name' : '账号创建',
            'key' : 'accCreateSelect',
            'path' : '/account_create/'
        },
        {
            'name' : '账号修改',
            'key' : 'accUpdateSelect',
            'path' : '/account_update/'
        },
        {
            'name' : '账号删除',
            'key' : 'accDelSelect',
            'path' : '/account_delete/'
        },
        {
            'name' : '账号操作日志',
            'key' : 'accLogSelect',
            'path' : '/account_log/'
        }
    ]
]

SERVER_SELECT_LIST = [
    [
        {
            'name': '游戏配置管理',
            'key' : 'title',
            'path' : 'cfgid'
        },
        {
            'name' : '配置展示',
            'key' : 'svrShowCfg',
            'path' : '/server_showcfg/'
        },
        {
            'name' : '添加配置',
            'key' : 'svrAddCfg',
            'path' : '/server_addcfg/'
        },
        {
            'name' : '查看配置操作日志',
            'key' : 'svrLogCfg',
            'path' : '/server_logcfg/'
        },
    ], 
    [
        {
            'name': '服务器管理',
            'key' : 'title',
            'path' : 'svrid'
        },
        {
            'name' : '区服展示',
            'key' : 'svrShowGrp',
            'path' : '/server_showgrp/'
        },
        {
            'name' : '开启新区',
            'key' : 'svrOpenGrp',
            'path' : '/server_opengrp/'
        },
        {
            'name' : '合并区服',
            'key' : 'svrMergeGrp',
            'path' : '/server_mergeGrp/'
        },
    ]
]

#邮件管理
MAIL_SELECT_LIST = [
    [
        {
            'name': '邮件操作管理',
            'key' : 'title',
            'path' : 'mailoptid'
        },
        {
            'name' : '邮件展示',
            'key' : 'mailShowSelect',
            'path' : '/mail_show/'
        },
        {
            'name' : '添加邮件',
            'key' : 'mailCreateSelect',
            'path' : '/mail_create/'
        },
        {
            'name' : '邮件操作日志',
            'key' : 'mailLogSelect',
            'path' : '/mail_log/'
        }
    ]
]

