# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_module_hero.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15msg_module_hero.proto\x12\x08ProtoMsg\"\xa4\x01\n\x0eMsgModule_Hero\"\x91\x01\n\x06MsgCmd\x12\x11\n\rMsg_Hero_None\x10\x00\x12\x1c\n\x18Msg_Hero_UpHeroLevel_Req\x10\x01\x12\x1c\n\x18Msg_Hero_UpHeroLevel_Rsp\x10\x02\x12\x1b\n\x17Msg_Hero_UpHeroStar_Req\x10\x03\x12\x1b\n\x17Msg_Hero_UpHeroStar_Rsp\x10\x04\",\n\x18Msg_Hero_UpHeroLevel_Req\x12\x10\n\x08uiHeroId\x18\x01 \x01(\r\".\n\x18Msg_Hero_UpHeroLevel_Rsp\x12\x12\n\nuiCurLevel\x18\x01 \x01(\r\"+\n\x17Msg_Hero_UpHeroStar_Req\x12\x10\n\x08uiHeroId\x18\x01 \x01(\r\",\n\x17Msg_Hero_UpHeroStar_Rsp\x12\x11\n\tuiCurStar\x18\x01 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msg_module_hero_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MSGMODULE_HERO._serialized_start=36
  _MSGMODULE_HERO._serialized_end=200
  _MSGMODULE_HERO_MSGCMD._serialized_start=55
  _MSGMODULE_HERO_MSGCMD._serialized_end=200
  _MSG_HERO_UPHEROLEVEL_REQ._serialized_start=202
  _MSG_HERO_UPHEROLEVEL_REQ._serialized_end=246
  _MSG_HERO_UPHEROLEVEL_RSP._serialized_start=248
  _MSG_HERO_UPHEROLEVEL_RSP._serialized_end=294
  _MSG_HERO_UPHEROSTAR_REQ._serialized_start=296
  _MSG_HERO_UPHEROSTAR_REQ._serialized_end=339
  _MSG_HERO_UPHEROSTAR_RSP._serialized_start=341
  _MSG_HERO_UPHEROSTAR_RSP._serialized_end=385
# @@protoc_insertion_point(module_scope)
