# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server_common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import msg_common_pb2 as msg__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13server_common.proto\x12\x08ProtoMsg\x1a\x10msg_common.proto\"\xd9\x02\n\x0fSvr_Player_Info\x12\x12\n\nllPlayerId\x18\x01 \x01(\x03\x12\x15\n\rstrPlayerName\x18\x02 \x01(\t\x12\x0f\n\x07uiLevel\x18\x03 \x01(\r\x12\x10\n\x08uiGender\x18\x04 \x01(\r\x12.\n\rePlayerStatus\x18\x05 \x01(\x0e\x32\x17.ProtoMsg.EPlayerStatus\x12\x14\n\x0cllLogoutTime\x18\x06 \x01(\x03\x12\x10\n\x08uiGameId\x18\x07 \x01(\r\x12\x10\n\x08uiGateId\x18\x08 \x01(\r\x12\x10\n\x08strDevId\x18\t \x01(\t\x12\x12\n\nstrChannel\x18\n \x01(\t\x12\x13\n\x0bstrClientIp\x18\x0b \x01(\t\x12\x13\n\x0bstrCityCode\x18\x0c \x01(\t\x12\x12\n\nstrAccName\x18\r \x01(\t\x12\x15\n\rstrAppVersion\x18\x0e \x01(\t\x12\x13\n\x0bllLoginTime\x18\x0f \x01(\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SVR_PLAYER_INFO._serialized_start=52
  _SVR_PLAYER_INFO._serialized_end=397
# @@protoc_insertion_point(module_scope)
