# Generated by Django 4.2 on 2023-04-25 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_xmlcfg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Xmlcfg',
        ),
    ]
