// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_module_ranker.proto

#include "msg_module_ranker.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace ProtoMsg {
PROTOBUF_CONSTEXPR MsgModule_Ranker::MsgModule_Ranker(
    ::_pbi::ConstantInitialized){}
struct MsgModule_RankerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MsgModule_RankerDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MsgModule_RankerDefaultTypeInternal() {}
  union {
    MsgModule_Ranker _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MsgModule_RankerDefaultTypeInternal _MsgModule_Ranker_default_instance_;
PROTOBUF_CONSTEXPR ranker_info_t::ranker_info_t(
    ::_pbi::ConstantInitialized)
  : strname_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , lluserid_(int64_t{0})
  , irank_(0)
  , iscore_(0)
  , iheadid_(0)
  , iframeid_(0)
  , ilevel_(0){}
struct ranker_info_tDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ranker_info_tDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ranker_info_tDefaultTypeInternal() {}
  union {
    ranker_info_t _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ranker_info_tDefaultTypeInternal _ranker_info_t_default_instance_;
PROTOBUF_CONSTEXPR Msg_Ranker_GetRankerList_Req::Msg_Ranker_GetRankerList_Req(
    ::_pbi::ConstantInitialized){}
struct Msg_Ranker_GetRankerList_ReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Msg_Ranker_GetRankerList_ReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Msg_Ranker_GetRankerList_ReqDefaultTypeInternal() {}
  union {
    Msg_Ranker_GetRankerList_Req _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Msg_Ranker_GetRankerList_ReqDefaultTypeInternal _Msg_Ranker_GetRankerList_Req_default_instance_;
PROTOBUF_CONSTEXPR Msg_Ranker_GetRankerList_Rsp::Msg_Ranker_GetRankerList_Rsp(
    ::_pbi::ConstantInitialized)
  : vecrankerlist_()
  , oownranker_(nullptr){}
struct Msg_Ranker_GetRankerList_RspDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Msg_Ranker_GetRankerList_RspDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Msg_Ranker_GetRankerList_RspDefaultTypeInternal() {}
  union {
    Msg_Ranker_GetRankerList_Rsp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Msg_Ranker_GetRankerList_RspDefaultTypeInternal _Msg_Ranker_GetRankerList_Rsp_default_instance_;
}  // namespace ProtoMsg
static ::_pb::Metadata file_level_metadata_msg_5fmodule_5franker_2eproto[4];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_msg_5fmodule_5franker_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_msg_5fmodule_5franker_2eproto = nullptr;

const uint32_t TableStruct_msg_5fmodule_5franker_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ProtoMsg::MsgModule_Ranker, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ProtoMsg::ranker_info_t, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ProtoMsg::ranker_info_t, irank_),
  PROTOBUF_FIELD_OFFSET(::ProtoMsg::ranker_info_t, lluserid_),
  PROTOBUF_FIELD_OFFSET(::ProtoMsg::ranker_info_t, iscore_),
  PROTOBUF_FIELD_OFFSET(::ProtoMsg::ranker_info_t, iheadid_),
  PROTOBUF_FIELD_OFFSET(::ProtoMsg::ranker_info_t, iframeid_),
  PROTOBUF_FIELD_OFFSET(::ProtoMsg::ranker_info_t, ilevel_),
  PROTOBUF_FIELD_OFFSET(::ProtoMsg::ranker_info_t, strname_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ProtoMsg::Msg_Ranker_GetRankerList_Req, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ProtoMsg::Msg_Ranker_GetRankerList_Rsp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ProtoMsg::Msg_Ranker_GetRankerList_Rsp, oownranker_),
  PROTOBUF_FIELD_OFFSET(::ProtoMsg::Msg_Ranker_GetRankerList_Rsp, vecrankerlist_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ProtoMsg::MsgModule_Ranker)},
  { 6, -1, -1, sizeof(::ProtoMsg::ranker_info_t)},
  { 19, -1, -1, sizeof(::ProtoMsg::Msg_Ranker_GetRankerList_Req)},
  { 25, -1, -1, sizeof(::ProtoMsg::Msg_Ranker_GetRankerList_Rsp)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::ProtoMsg::_MsgModule_Ranker_default_instance_._instance,
  &::ProtoMsg::_ranker_info_t_default_instance_._instance,
  &::ProtoMsg::_Msg_Ranker_GetRankerList_Req_default_instance_._instance,
  &::ProtoMsg::_Msg_Ranker_GetRankerList_Rsp_default_instance_._instance,
};

const char descriptor_table_protodef_msg_5fmodule_5franker_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\027msg_module_ranker.proto\022\010ProtoMsg\"u\n\020M"
  "sgModule_Ranker\"a\n\006MsgCmd\022\023\n\017Msg_Ranker_"
  "None\020\000\022 \n\034Msg_Ranker_GetRankerList_Req\020\001"
  "\022 \n\034Msg_Ranker_GetRankerList_Rsp\020\002\"\204\001\n\rr"
  "anker_info_t\022\r\n\005iRank\030\001 \001(\005\022\020\n\010llUserId\030"
  "\002 \001(\003\022\016\n\006iScore\030\003 \001(\005\022\017\n\007iHeadId\030\004 \001(\005\022\020"
  "\n\010iFrameId\030\005 \001(\005\022\016\n\006iLevel\030\006 \001(\005\022\017\n\007strN"
  "ame\030\007 \001(\t\"\036\n\034Msg_Ranker_GetRankerList_Re"
  "q\"{\n\034Msg_Ranker_GetRankerList_Rsp\022+\n\noOw"
  "nRanker\030\001 \001(\0132\027.ProtoMsg.ranker_info_t\022."
  "\n\rvecRankerList\030\002 \003(\0132\027.ProtoMsg.ranker_"
  "info_tb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_msg_5fmodule_5franker_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_msg_5fmodule_5franker_2eproto = {
    false, false, 454, descriptor_table_protodef_msg_5fmodule_5franker_2eproto,
    "msg_module_ranker.proto",
    &descriptor_table_msg_5fmodule_5franker_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_msg_5fmodule_5franker_2eproto::offsets,
    file_level_metadata_msg_5fmodule_5franker_2eproto, file_level_enum_descriptors_msg_5fmodule_5franker_2eproto,
    file_level_service_descriptors_msg_5fmodule_5franker_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_msg_5fmodule_5franker_2eproto_getter() {
  return &descriptor_table_msg_5fmodule_5franker_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_msg_5fmodule_5franker_2eproto(&descriptor_table_msg_5fmodule_5franker_2eproto);
namespace ProtoMsg {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MsgModule_Ranker_MsgCmd_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_msg_5fmodule_5franker_2eproto);
  return file_level_enum_descriptors_msg_5fmodule_5franker_2eproto[0];
}
bool MsgModule_Ranker_MsgCmd_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr MsgModule_Ranker_MsgCmd MsgModule_Ranker::Msg_Ranker_None;
constexpr MsgModule_Ranker_MsgCmd MsgModule_Ranker::Msg_Ranker_GetRankerList_Req;
constexpr MsgModule_Ranker_MsgCmd MsgModule_Ranker::Msg_Ranker_GetRankerList_Rsp;
constexpr MsgModule_Ranker_MsgCmd MsgModule_Ranker::MsgCmd_MIN;
constexpr MsgModule_Ranker_MsgCmd MsgModule_Ranker::MsgCmd_MAX;
constexpr int MsgModule_Ranker::MsgCmd_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class MsgModule_Ranker::_Internal {
 public:
};

MsgModule_Ranker::MsgModule_Ranker(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:ProtoMsg.MsgModule_Ranker)
}
MsgModule_Ranker::MsgModule_Ranker(const MsgModule_Ranker& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:ProtoMsg.MsgModule_Ranker)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MsgModule_Ranker::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MsgModule_Ranker::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata MsgModule_Ranker::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_msg_5fmodule_5franker_2eproto_getter, &descriptor_table_msg_5fmodule_5franker_2eproto_once,
      file_level_metadata_msg_5fmodule_5franker_2eproto[0]);
}

// ===================================================================

class ranker_info_t::_Internal {
 public:
};

ranker_info_t::ranker_info_t(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:ProtoMsg.ranker_info_t)
}
ranker_info_t::ranker_info_t(const ranker_info_t& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  strname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    strname_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_strname().empty()) {
    strname_.Set(from._internal_strname(), 
      GetArenaForAllocation());
  }
  ::memcpy(&lluserid_, &from.lluserid_,
    static_cast<size_t>(reinterpret_cast<char*>(&ilevel_) -
    reinterpret_cast<char*>(&lluserid_)) + sizeof(ilevel_));
  // @@protoc_insertion_point(copy_constructor:ProtoMsg.ranker_info_t)
}

inline void ranker_info_t::SharedCtor() {
strname_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  strname_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&lluserid_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&ilevel_) -
    reinterpret_cast<char*>(&lluserid_)) + sizeof(ilevel_));
}

ranker_info_t::~ranker_info_t() {
  // @@protoc_insertion_point(destructor:ProtoMsg.ranker_info_t)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ranker_info_t::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  strname_.Destroy();
}

void ranker_info_t::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ranker_info_t::Clear() {
// @@protoc_insertion_point(message_clear_start:ProtoMsg.ranker_info_t)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  strname_.ClearToEmpty();
  ::memset(&lluserid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ilevel_) -
      reinterpret_cast<char*>(&lluserid_)) + sizeof(ilevel_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ranker_info_t::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 iRank = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          irank_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 llUserId = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          lluserid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 iScore = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          iscore_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 iHeadId = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          iheadid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 iFrameId = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          iframeid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 iLevel = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          ilevel_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string strName = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_strname();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ProtoMsg.ranker_info_t.strName"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ranker_info_t::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ProtoMsg.ranker_info_t)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 iRank = 1;
  if (this->_internal_irank() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_irank(), target);
  }

  // int64 llUserId = 2;
  if (this->_internal_lluserid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_lluserid(), target);
  }

  // int32 iScore = 3;
  if (this->_internal_iscore() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_iscore(), target);
  }

  // int32 iHeadId = 4;
  if (this->_internal_iheadid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_iheadid(), target);
  }

  // int32 iFrameId = 5;
  if (this->_internal_iframeid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_iframeid(), target);
  }

  // int32 iLevel = 6;
  if (this->_internal_ilevel() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(6, this->_internal_ilevel(), target);
  }

  // string strName = 7;
  if (!this->_internal_strname().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_strname().data(), static_cast<int>(this->_internal_strname().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ProtoMsg.ranker_info_t.strName");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_strname(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ProtoMsg.ranker_info_t)
  return target;
}

size_t ranker_info_t::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ProtoMsg.ranker_info_t)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string strName = 7;
  if (!this->_internal_strname().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_strname());
  }

  // int64 llUserId = 2;
  if (this->_internal_lluserid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_lluserid());
  }

  // int32 iRank = 1;
  if (this->_internal_irank() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_irank());
  }

  // int32 iScore = 3;
  if (this->_internal_iscore() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_iscore());
  }

  // int32 iHeadId = 4;
  if (this->_internal_iheadid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_iheadid());
  }

  // int32 iFrameId = 5;
  if (this->_internal_iframeid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_iframeid());
  }

  // int32 iLevel = 6;
  if (this->_internal_ilevel() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_ilevel());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ranker_info_t::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ranker_info_t::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ranker_info_t::GetClassData() const { return &_class_data_; }

void ranker_info_t::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<ranker_info_t *>(to)->MergeFrom(
      static_cast<const ranker_info_t &>(from));
}


void ranker_info_t::MergeFrom(const ranker_info_t& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ProtoMsg.ranker_info_t)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_strname().empty()) {
    _internal_set_strname(from._internal_strname());
  }
  if (from._internal_lluserid() != 0) {
    _internal_set_lluserid(from._internal_lluserid());
  }
  if (from._internal_irank() != 0) {
    _internal_set_irank(from._internal_irank());
  }
  if (from._internal_iscore() != 0) {
    _internal_set_iscore(from._internal_iscore());
  }
  if (from._internal_iheadid() != 0) {
    _internal_set_iheadid(from._internal_iheadid());
  }
  if (from._internal_iframeid() != 0) {
    _internal_set_iframeid(from._internal_iframeid());
  }
  if (from._internal_ilevel() != 0) {
    _internal_set_ilevel(from._internal_ilevel());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ranker_info_t::CopyFrom(const ranker_info_t& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ProtoMsg.ranker_info_t)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ranker_info_t::IsInitialized() const {
  return true;
}

void ranker_info_t::InternalSwap(ranker_info_t* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &strname_, lhs_arena,
      &other->strname_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ranker_info_t, ilevel_)
      + sizeof(ranker_info_t::ilevel_)
      - PROTOBUF_FIELD_OFFSET(ranker_info_t, lluserid_)>(
          reinterpret_cast<char*>(&lluserid_),
          reinterpret_cast<char*>(&other->lluserid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ranker_info_t::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_msg_5fmodule_5franker_2eproto_getter, &descriptor_table_msg_5fmodule_5franker_2eproto_once,
      file_level_metadata_msg_5fmodule_5franker_2eproto[1]);
}

// ===================================================================

class Msg_Ranker_GetRankerList_Req::_Internal {
 public:
};

Msg_Ranker_GetRankerList_Req::Msg_Ranker_GetRankerList_Req(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:ProtoMsg.Msg_Ranker_GetRankerList_Req)
}
Msg_Ranker_GetRankerList_Req::Msg_Ranker_GetRankerList_Req(const Msg_Ranker_GetRankerList_Req& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:ProtoMsg.Msg_Ranker_GetRankerList_Req)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Msg_Ranker_GetRankerList_Req::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Msg_Ranker_GetRankerList_Req::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata Msg_Ranker_GetRankerList_Req::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_msg_5fmodule_5franker_2eproto_getter, &descriptor_table_msg_5fmodule_5franker_2eproto_once,
      file_level_metadata_msg_5fmodule_5franker_2eproto[2]);
}

// ===================================================================

class Msg_Ranker_GetRankerList_Rsp::_Internal {
 public:
  static const ::ProtoMsg::ranker_info_t& oownranker(const Msg_Ranker_GetRankerList_Rsp* msg);
};

const ::ProtoMsg::ranker_info_t&
Msg_Ranker_GetRankerList_Rsp::_Internal::oownranker(const Msg_Ranker_GetRankerList_Rsp* msg) {
  return *msg->oownranker_;
}
Msg_Ranker_GetRankerList_Rsp::Msg_Ranker_GetRankerList_Rsp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  vecrankerlist_(arena) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:ProtoMsg.Msg_Ranker_GetRankerList_Rsp)
}
Msg_Ranker_GetRankerList_Rsp::Msg_Ranker_GetRankerList_Rsp(const Msg_Ranker_GetRankerList_Rsp& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      vecrankerlist_(from.vecrankerlist_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_oownranker()) {
    oownranker_ = new ::ProtoMsg::ranker_info_t(*from.oownranker_);
  } else {
    oownranker_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:ProtoMsg.Msg_Ranker_GetRankerList_Rsp)
}

inline void Msg_Ranker_GetRankerList_Rsp::SharedCtor() {
oownranker_ = nullptr;
}

Msg_Ranker_GetRankerList_Rsp::~Msg_Ranker_GetRankerList_Rsp() {
  // @@protoc_insertion_point(destructor:ProtoMsg.Msg_Ranker_GetRankerList_Rsp)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Msg_Ranker_GetRankerList_Rsp::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete oownranker_;
}

void Msg_Ranker_GetRankerList_Rsp::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Msg_Ranker_GetRankerList_Rsp::Clear() {
// @@protoc_insertion_point(message_clear_start:ProtoMsg.Msg_Ranker_GetRankerList_Rsp)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  vecrankerlist_.Clear();
  if (GetArenaForAllocation() == nullptr && oownranker_ != nullptr) {
    delete oownranker_;
  }
  oownranker_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Msg_Ranker_GetRankerList_Rsp::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .ProtoMsg.ranker_info_t oOwnRanker = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_oownranker(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .ProtoMsg.ranker_info_t vecRankerList = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_vecrankerlist(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Msg_Ranker_GetRankerList_Rsp::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ProtoMsg.Msg_Ranker_GetRankerList_Rsp)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .ProtoMsg.ranker_info_t oOwnRanker = 1;
  if (this->_internal_has_oownranker()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::oownranker(this),
        _Internal::oownranker(this).GetCachedSize(), target, stream);
  }

  // repeated .ProtoMsg.ranker_info_t vecRankerList = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_vecrankerlist_size()); i < n; i++) {
    const auto& repfield = this->_internal_vecrankerlist(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ProtoMsg.Msg_Ranker_GetRankerList_Rsp)
  return target;
}

size_t Msg_Ranker_GetRankerList_Rsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ProtoMsg.Msg_Ranker_GetRankerList_Rsp)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .ProtoMsg.ranker_info_t vecRankerList = 2;
  total_size += 1UL * this->_internal_vecrankerlist_size();
  for (const auto& msg : this->vecrankerlist_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // .ProtoMsg.ranker_info_t oOwnRanker = 1;
  if (this->_internal_has_oownranker()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *oownranker_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Msg_Ranker_GetRankerList_Rsp::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Msg_Ranker_GetRankerList_Rsp::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Msg_Ranker_GetRankerList_Rsp::GetClassData() const { return &_class_data_; }

void Msg_Ranker_GetRankerList_Rsp::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Msg_Ranker_GetRankerList_Rsp *>(to)->MergeFrom(
      static_cast<const Msg_Ranker_GetRankerList_Rsp &>(from));
}


void Msg_Ranker_GetRankerList_Rsp::MergeFrom(const Msg_Ranker_GetRankerList_Rsp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ProtoMsg.Msg_Ranker_GetRankerList_Rsp)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  vecrankerlist_.MergeFrom(from.vecrankerlist_);
  if (from._internal_has_oownranker()) {
    _internal_mutable_oownranker()->::ProtoMsg::ranker_info_t::MergeFrom(from._internal_oownranker());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Msg_Ranker_GetRankerList_Rsp::CopyFrom(const Msg_Ranker_GetRankerList_Rsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ProtoMsg.Msg_Ranker_GetRankerList_Rsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Msg_Ranker_GetRankerList_Rsp::IsInitialized() const {
  return true;
}

void Msg_Ranker_GetRankerList_Rsp::InternalSwap(Msg_Ranker_GetRankerList_Rsp* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  vecrankerlist_.InternalSwap(&other->vecrankerlist_);
  swap(oownranker_, other->oownranker_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Msg_Ranker_GetRankerList_Rsp::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_msg_5fmodule_5franker_2eproto_getter, &descriptor_table_msg_5fmodule_5franker_2eproto_once,
      file_level_metadata_msg_5fmodule_5franker_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace ProtoMsg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ProtoMsg::MsgModule_Ranker*
Arena::CreateMaybeMessage< ::ProtoMsg::MsgModule_Ranker >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ProtoMsg::MsgModule_Ranker >(arena);
}
template<> PROTOBUF_NOINLINE ::ProtoMsg::ranker_info_t*
Arena::CreateMaybeMessage< ::ProtoMsg::ranker_info_t >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ProtoMsg::ranker_info_t >(arena);
}
template<> PROTOBUF_NOINLINE ::ProtoMsg::Msg_Ranker_GetRankerList_Req*
Arena::CreateMaybeMessage< ::ProtoMsg::Msg_Ranker_GetRankerList_Req >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ProtoMsg::Msg_Ranker_GetRankerList_Req >(arena);
}
template<> PROTOBUF_NOINLINE ::ProtoMsg::Msg_Ranker_GetRankerList_Rsp*
Arena::CreateMaybeMessage< ::ProtoMsg::Msg_Ranker_GetRankerList_Rsp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ProtoMsg::Msg_Ranker_GetRankerList_Rsp >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
